namespace TasksEpam.Project3
{
    using System.Collections.Generic;

    /// <summary>
    /// Documentation for the Person.
    /// </summary>
    public class Person
    {
        /// <auto-generated />
        public string Name { get; set; }

        /// <auto-generated />
        public int Age { get; set; }

        /// <auto-generated />
        public IEnumerable<string> PhoneNumbers { get; set; }
    }
}
